# Generated by Django 4.0.1 on 2022-01-06 22:22

from django.db import migrations, models
import django.db.models.deletion
import quiz.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_choice_body_alter_choice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.helpers.RandomFileName('choices')),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.helpers.RandomFileName('questions')),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Correct?')),
                ('student_answer', models.TextField(verbose_name='Answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='topic')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
    ]
