# Generated by Django 4.0.1 on 2022-01-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_choice_image_alter_question_image_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
    ]
