# Generated by Django 4.0.1 on 2022-01-11 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_alter_answer_question_alter_answer_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='student_answer',
            new_name='user_answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answer', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(max_length=75)),
                ('country', models.CharField(max_length=75)),
                ('how_did_you_hear_about_us', models.CharField(max_length=350)),
                ('phone_number', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('birth_date', models.DateField()),
                ('school_type', models.CharField(choices=[('NAT_AR', 'National Arabic'), ('NAT_ENG', 'National English'), ('US', 'American'), ('IG', 'IG'), ('OTHER', 'Other')], default='NAT_AR', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
