# Generated by Django 4.0.1 on 2022-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_student_answer_answer_user_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='how_did_you_hear_about_us',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(max_length=75),
        ),
    ]
